name: dbt CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main

jobs:
  dbt-ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          pip install dbt-databricks

      - name: Install Packages
        run: |
          dbt deps

      - name: Parse Project
        run: |
          dbt parse

      - name: Compile Project
        run: |
          dbt compile