name: dbt CI

on:
  push:
    branches:
      - main
      - feature/**

  pull_request:
    branches:
      - main

jobs:
  dbt-ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          pip install dbt-databricks

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt

          cat <<EOF > ~/.dbt/profiles.yml
          denorm_to_norm:
            target: dev
            outputs:
              dev:
                type: databricks
                host: ${{ secrets.DATABRICKS_HOST }}
                http_path: ${{ secrets.DATABRICKS_HTTP_PATH }}
                token: ${{ secrets.DATABRICKS_TOKEN }}
                catalog: ${{ secrets.DATABRICKS_CATALOG }}
                schema: ${{ secrets.DATABRICKS_SCHEMA }}
                threads: 1
          EOF

      - name: Validate Connection
        run: |
          dbt debug

      - name: Install Packages
        run: |
          dbt deps

      - name: Parse Project
        run: |
          dbt parse

      - name: Compile Project
        run: |
          dbt compile